### ISSUE TITLE
error in isntalling native dependencies.

### ISSUE THREAD

**Issue by navneetccna** [jaganathanb/vilaippattiyal#1]
Node Vesion : v8.11.3

when i run following commands 

**cd src
yarn install**

$ npm run electron-rebuild

> electron-react-boilerplate@1.0.0 electron-rebuild /home/owner/projects/vilaippattiyal/src
> node -r babel-register ../internals/scripts/ElectronRebuild.js

/bin/sh: 1: ../node_modules/.bin/electron-rebuild.cmd: not found
child_process.js:644
    throw err;
    ^

Error: Command failed: ../node_modules/.bin/electron-rebuild.cmd --parallel --force --types prod,dev,optional --module-dir .
/bin/sh: 1: ../node_modules/.bin/electron-rebuild.cmd: not found

    at checkExecSyncError (child_process.js:601:13)
    at execSync (child_process.js:641:13)
    at Object.<anonymous> (/home/owner/projects/vilaippattiyal/internals/scripts/ElectronRebuild.js:21:3)
    at Module._compile (module.js:652:30)
    at loader (/home/owner/projects/vilaippattiyal/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/owner/projects/vilaippattiyal/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-react-boilerplate@1.0.0 electron-rebuild: `node -r babel-register ../internals/scripts/ElectronRebuild.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-react-boilerplate@1.0.0 electron-rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/owner/.npm/_logs/2018-08-09T12_42_16_331Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by jaganathanb** [comment]
Could not reproduce the issue. 

Did you installed the app dependencies before installing the native dependencies?

**Comment by navneetccna** [comment]
Yes, I installed app dependencies before native dependencies.
